wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.17
    code_path: code/ppo.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.13
    start_time: 1654526130
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      3:
      - 13
      - 16
      - 35
      4: 3.8.13
      5: 0.12.17
      8:
      - 5
anneal_lr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 64
capture_video:
  desc: null
  value: false
checkpoint_interval:
  desc: null
  value: 500
checkpoint_path:
  desc: null
  value: /private/home/samvelyan/grafter
clip_coef:
  desc: null
  value: 0.2
clip_vloss:
  desc: null
  value: true
cuda:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
exp_name:
  desc: null
  value: ppo
gae:
  desc: null
  value: true
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.99
height:
  desc: null
  value: 30
learning_rate:
  desc: null
  value: 0.00025
max_grad_norm:
  desc: null
  value: 0.5
minibatch_size:
  desc: null
  value: 16
norm_adv:
  desc: null
  value: true
num_envs:
  desc: null
  value: 2
num_minibatches:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 32
observer_type:
  desc: null
  value: Vector
seed:
  desc: null
  value: 1
target_kl:
  desc: null
  value: null
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 50000000
track:
  desc: null
  value: true
update_epochs:
  desc: null
  value: 4
vf_coef:
  desc: null
  value: 0.5
wandb_entity:
  desc: null
  value: griddlyjs
wandb_group:
  desc: null
  value: Default
wandb_project_name:
  desc: null
  value: EscapeRoom
width:
  desc: null
  value: 30
